### ISSUE TITLE
visualception methods not being added to $I

### ISSUE THREAD

**Issue by arifmasood** [Codeception/VisualCeption#41]
Following Installation steps followed..

- php-imagick extension successfully installed and verified
- composer require "codeception/visualception:*" --dev added to composer.json. composer updated.

Visualception added to web.suite.yml like below..

```
class_name: WebGuy
modules:
  enabled: [WebDriver, WebHelper, Asserts, VisualCeption]
  config:
    WebDriver:
      url: https://www.abc.xyz/
      host: 127.0.0.1 # local address
      port: 4444 # selenium port
      browser: chrome
      window_size: maximize
      restart: true # sse a new browser window for each test 
    VisualCeption:
      maximumDeviation: 5                                   # deviation in percent
      saveCurrentImageIfFailure: false                       # if true, VisualCeption saves the current
```

I can see the visualception under vendor>codeception. However I can not access any of visualception methods via $I (whereas rest of codeception methods working fine).
