### ISSUE TITLE
Blank images from current views ...

### ISSUE THREAD

**Issue by teratux** [Codeception/VisualCeption#43]
Hello ... I'm currently using VisualCeption to see if the original design specifications are met in every page of my website.   I followed the install and configuration guidelines and it is up and running.  This is the configuration I used in my acceptance suite:

```
- VisualCeption:
            referenceImageDir: 'referenceObjects/'
            currentImageDir: 'currentObjects/'
            report: true
            maximumDeviation: 5                                   # deviation in percent
            saveCurrentImageIfFailure: true                       # if true, VisualCeption saves the current
```

This correctly produces a **tests/_data/referenceObjects** directory where I can store my original element designs and it also produces a **tests/_output/currentObjects** directory where the current items from my pages are stored.

The problem lies when I run my test.  The DOM element is being identified correctly but the produced image is blank with the correct dimensions.  For example, this is my test:

 ```
   public function visualMatch(AcceptanceTester $I)
    {
        $I->resizeWindow(1024,762);
        $I->maximizeWindow();
        $I->amOnPage('/general_info/promotions');
        $I->seeVisualChanges( "promotion_icon", ".image-plan" );
    }
```

There is an element with a class **.image-plan** that has a background image and promotion_icon is an image file called: **testFrontendCest.visualMatch.promotion_icon.png** in the referenceObjects directory.  The result comparison is in this link [Visualcept blank](https://pasteboard.co/HGLJWDP.jpg) and as you can see the original is being loaded and compared to a blank image.  This [Screenshot](https://pasteboard.co/HGLKJCC.png) is the produced screenshot with the Recorder extension. 

I'm using Webdriver and PhantomJS.

Thanks in advance
